# Generated by Django 3.1.4 on 2021-01-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='this is a title', max_length=50),
            preserve_default=False,
        ),
    ]
